service: characters

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-2
  stage: ${env:STAGE, 'development'}
  environment:
    STAGE: ${env:STAGE, 'development'}

functions:
  app:
    handler: index.handler
    events:
    - http:
        path: /getBinSamples
        method: get
        cors: true
    - http:
        path: /submitTest
        method: post
        cors: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    port: 3001
