service: characters

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-southeast-2
  stage: ${env:STAGE, 'development'}
  environment:
    STAGE: ${env:STAGE, 'development'}
    STATE_ENCRYPTION_KEY: ${env:STATE_ENCRYPTION_KEY,'cc6254c878e0dfd4fc34b51aea03805e'}
    STATE_ENCRYPTION_IV: ${env:STATE_ENCRYPTION_IV,'6c8eeb5616ee85acffca94ccaca25376'}
    SKRITTER_OAUTH_CLIENT_NAME: ${env:SKRITTER_OAUTH_CLIENT_NAME}
    SKRITTER_OAUTH_CLIENT_SECRET: ${env:SKRITTER_OAUTH_CLIENT_SECRET}
    SKRITTER_OAUTH_REDIRECT_URI: 'http://staging.hanzishan.com/'

functions:
  app:
    handler: index.handler
    events:
    - http:
        path: /getCharacterSample
        method: get
    - http:
        path: /submitTest
        method: post
    - http:
        path: /skritter/oauth/token
        method: get
    - http:
        path: /skritter/characters
        method: post

plugins:
  - serverless-offline

custom:
  serverless-offline:
    port: 3001
