service: characters

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-2
  stage: ${env:STAGE, 'development'}
  environment:
    STAGE: ${env:STAGE, 'development'}
    TEST_RESULTS_BUCKET_NAME: '#{TestResultsBucket}'
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::#{TestResultsBucket}/*"

functions:
  app:
    handler: index.handler
    events:
    - http:
        path: /getBinSamples
        method: get
        cors: true
    - http:
        path: /submitTest
        method: post
        cors: true

resources:
  - ${file(resources/test-result-bucket.yml)}

plugins:
  - serverless-offline
  - serverless-pseudo-parameters

custom:
  serverless-offline:
    port: 3001
